# Site settings
title: ycw790710 github page
description: > # this means to ignore newlines until "baseurl:"
  -
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://ycw790710.github.io" # the base hostname & protocol for your site
